//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilLetter
    {
        public long ID { get; set; }
        public string CaseNo { get; set; }
        public string CaseType { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public int DocketFrom { get; set; }
        public string Judge { get; set; }
        public Nullable<System.DateTime> ServDate { get; set; }
        public Nullable<double> PrayerAmt { get; set; }
        public string CaseDesignation { get; set; }
        public string FirstName { get; set; }
        public string MInit { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string BarCode { get; set; }
        public string HumanReadable { get; set; }
        public string Country { get; set; }
        public string Plaintiff { get; set; }
        public string PlaintAddr { get; set; }
        public string PlainAtt { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<bool> Merge { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> DatePrt { get; set; }
        public string BatchName { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
