//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashRpt
    {
        public long ID { get; set; }
        public long CrashRptNo { get; set; }
        public string LocalRptNum { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<int> HitSkip { get; set; }
        public string RptAgencyNIC { get; set; }
        public string RptAgencyName { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<int> UnitError { get; set; }
        public string County { get; set; }
        public string CVTName { get; set; }
        public Nullable<System.DateTime> CrashDate { get; set; }
        public Nullable<System.DateTime> CrashTm { get; set; }
        public string Narrative { get; set; }
        public string PDFName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual CrashRptSeverity CrashRptSeverity { get; set; }
    }
}
