//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashRptOccup
    {
        public long ID { get; set; }
        public long CrashRptNo { get; set; }
        public int VehicleNo { get; set; }
        public Nullable<int> OccupNo { get; set; }
        public string OccupFName { get; set; }
        public string OccupMName { get; set; }
        public string OccupLName { get; set; }
        public string OFullName { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string OccupAddr { get; set; }
        public string OccupCity { get; set; }
        public string OccupState { get; set; }
        public string OccupZip { get; set; }
        public string OFullAddr { get; set; }
        public Nullable<System.DateTime> OccupDOB { get; set; }
        public Nullable<int> OccupAge { get; set; }
        public string OccupGender { get; set; }
        public string OccupPhone { get; set; }
        public Nullable<int> OccupInjuries { get; set; }
        public Nullable<int> WSeatPos { get; set; }
        public string BarCode { get; set; }
        public string HumanReadable { get; set; }
        public Nullable<bool> Merge { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> DatePrt { get; set; }
        public string PrtBatch { get; set; }
        public string TrackID { get; set; }
    
        public virtual CrashRptOccInjury CrashRptOccInjury { get; set; }
        public virtual CrashRptOccSeatPos CrashRptOccSeatPos { get; set; }
    }
}
