//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashRptMotorist
    {
        public long ID { get; set; }
        public long CrashRptNo { get; set; }
        public int VehicleNo { get; set; }
        public string MotFName { get; set; }
        public string MotMName { get; set; }
        public string MotLName { get; set; }
        public string MotFullName { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string MotAddr { get; set; }
        public string MotCity { get; set; }
        public string MotState { get; set; }
        public string MotZip { get; set; }
        public string MotFullAddr { get; set; }
        public Nullable<System.DateTime> MotDOB { get; set; }
        public Nullable<int> MotAge { get; set; }
        public string MotGender { get; set; }
        public string MotPhone { get; set; }
        public Nullable<int> MotInjuries { get; set; }
        public Nullable<int> SeatPos { get; set; }
        public string OLState { get; set; }
        public string OLNum { get; set; }
        public string OffChrg { get; set; }
        public string OffDesc { get; set; }
        public string CitNumber { get; set; }
        public string BarCode { get; set; }
        public string HumanReadable { get; set; }
        public Nullable<bool> Merge { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> DatePrt { get; set; }
        public string PrtBatch { get; set; }
        public string TrackID { get; set; }
    
        public virtual CrashRptOccInjury CrashRptOccInjury { get; set; }
        public virtual CrashRptOccSeatPos CrashRptOccSeatPos { get; set; }
    }
}
