//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashRptVeh
    {
        public long ID { get; set; }
        public long CrashRptNo { get; set; }
        public int VehicleNo { get; set; }
        public string OwnerLName { get; set; }
        public string OwnerFName { get; set; }
        public string OwnerMName { get; set; }
        public string OwnerFullName { get; set; }
        public string OwnerPhone { get; set; }
        public string OwnerAddr { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerZip { get; set; }
        public string OwnerFullAddr { get; set; }
        public string LPState { get; set; }
        public string LPNum { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Occupants { get; set; }
        public Nullable<int> VehYear { get; set; }
        public string VehMake { get; set; }
        public string VehModel { get; set; }
        public string VehColor { get; set; }
        public Nullable<int> DamScale { get; set; }
        public string InsName { get; set; }
        public string PolicyNum { get; set; }
        public Nullable<int> CargoBodyType { get; set; }
        public Nullable<int> TypeUse { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<int> SpecFunct { get; set; }
    
        public virtual CrashRptVehBody CrashRptVehBody { get; set; }
        public virtual CrashRptVehDamScale CrashRptVehDamScale { get; set; }
        public virtual CrashRptVehSpecFunc CrashRptVehSpecFunc { get; set; }
        public virtual CrashRptVehTypeUse CrashRptVehTypeUse { get; set; }
        public virtual CrashRptVehUnitType CrashRptVehUnitType { get; set; }
    }
}
