//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultSchedule
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> Recurrence { get; set; }
        public string RecurrenceType { get; set; }
        public Nullable<int> RecurrenceTypeCount { get; set; }
        public Nullable<int> Reminder { get; set; }
        public string Categorize { get; set; }
        public string CustomStyle { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public Nullable<System.DateTime> RecurrenceStartDate { get; set; }
        public Nullable<System.DateTime> RecurrenceEndDate { get; set; }
        public string RecurrenceRule { get; set; }
        public string PatientName { get; set; }
        public string AppointmentType { get; set; }
        public string StartTimeZone { get; set; }
        public string EndTimeZone { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
