//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Initals { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string PCLawPWD { get; set; }
        public string NeedlesName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
