//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_CN_Reason
    {
        public long ID { get; set; }
        public string CanDesc { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
