//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCallLogDelete
    {
        public Nullable<int> ID1 { get; set; }
        public long ID { get; set; }
        public string PNCID { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public string Address { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CallSource { get; set; }
        public string CaseType { get; set; }
        public string DocketFrom { get; set; }
        public string CaseNo { get; set; }
        public Nullable<int> ICStatus { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public Nullable<System.DateTime> SchedTime { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<bool> SchedCall { get; set; }
        public Nullable<System.DateTime> Tickler1 { get; set; }
        public Nullable<int> ApmtOffice { get; set; }
        public Nullable<int> LtrID { get; set; }
        public Nullable<bool> ApptNoShow { get; set; }
        public Nullable<System.DateTime> Tickler { get; set; }
        public Nullable<bool> Rescheduled { get; set; }
        public Nullable<System.DateTime> Tickler2 { get; set; }
        public Nullable<bool> NewClient { get; set; }
        public Nullable<bool> RetainLater { get; set; }
        public Nullable<System.DateTime> Tickler3 { get; set; }
        public Nullable<bool> ApptCan { get; set; }
        public Nullable<System.DateTime> Tickler4 { get; set; }
        public Nullable<bool> FollowUp { get; set; }
        public Nullable<System.DateTime> Tickler5 { get; set; }
        public Nullable<bool> CallBack { get; set; }
        public Nullable<System.DateTime> Tickler6 { get; set; }
        public Nullable<System.DateTime> ApptCanDate { get; set; }
        public Nullable<int> ApptCanReason { get; set; }
        public Nullable<System.DateTime> ReschedDate { get; set; }
        public Nullable<System.DateTime> ReschedTime { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<System.DateTime> FollowUpTime { get; set; }
        public Nullable<System.DateTime> NewClientDate { get; set; }
        public string PCLawID { get; set; }
        public string Details { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Details2 { get; set; }
        public string Details3 { get; set; }
        public string Details4 { get; set; }
        public string Details5 { get; set; }
        public string Details6 { get; set; }
        public Nullable<int> FollowupLst { get; set; }
        public Nullable<System.DateTime> TBCB { get; set; }
        public Nullable<System.DateTime> TBCBL { get; set; }
        public Nullable<System.DateTime> LstMod { get; set; }
        public Nullable<int> LstModEID { get; set; }
        public Nullable<bool> NotRetained { get; set; }
        public Nullable<int> CallCnt { get; set; }
        public Nullable<bool> TB_Dispute { get; set; }
        public Nullable<long> DucumentID { get; set; }
        public string Detail1 { get; set; }
        public Nullable<int> ConAtty { get; set; }
        public string EmailAddr { get; set; }
        public Nullable<int> YN9pm { get; set; }
        public string ConAttyLoc { get; set; }
        public Nullable<bool> Citrix { get; set; }
        public Nullable<System.DateTime> CitrixSDate { get; set; }
        public Nullable<System.DateTime> CitrixRDate { get; set; }
        public string Division { get; set; }
        public string TrackID { get; set; }
        public Nullable<bool> inNeedles { get; set; }
        public Nullable<int> NRReason { get; set; }
    }
}
