//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCallLog1
    {
        public int ID { get; set; }
        public string PNCID { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CallSource { get; set; }
        public string CaseType { get; set; }
        public string DocketFrom { get; set; }
        public string CaseNo { get; set; }
        public Nullable<int> ICStatus { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public Nullable<System.DateTime> SchedTime { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<bool> SchedCall { get; set; }
        public Nullable<bool> NewClient { get; set; }
        public Nullable<int> ApmtOffice { get; set; }
        public Nullable<int> LtrID { get; set; }
        public Nullable<System.DateTime> Tickler { get; set; }
        public Nullable<System.DateTime> ApptCanDate { get; set; }
        public Nullable<bool> ApptNoShow { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<bool> Rescheduled { get; set; }
        public Nullable<bool> ApptCan { get; set; }
        public Nullable<int> ApptCanReason { get; set; }
        public Nullable<System.DateTime> ReschedDate { get; set; }
        public Nullable<System.DateTime> ReschedTime { get; set; }
        public Nullable<System.DateTime> NewClientDate { get; set; }
        public Nullable<bool> RetainLater { get; set; }
        public string Details { get; set; }
    }
}
