//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCallLog
    {
        public long ID { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CallSource { get; set; }
        public string CaseType { get; set; }
        public string DocketFrom { get; set; }
        public string CaseNo { get; set; }
        public Nullable<int> ICStatus { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public System.TimeSpan SchedTime { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<bool> SchedCall { get; set; }
        public Nullable<System.DateTime> Tickler1 { get; set; }
        public Nullable<int> ApmtOffice { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public Nullable<long> DucumentID { get; set; }
        public Nullable<int> ConAtty { get; set; }
        public string EmailAddr { get; set; }
        public string ConAttyLoc { get; set; }
    }
}
