//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCallLogCB
    {
        public long IDCB { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> Tickler6 { get; set; }
        public string Detail6 { get; set; }
        public Nullable<System.DateTime> CurDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
