//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCallLogR
    {
        public long IDRS { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> ReschedDate { get; set; }
        public Nullable<System.DateTime> ReschedTime { get; set; }
        public Nullable<System.DateTime> Tickler2 { get; set; }
        public string Detail2 { get; set; }
        public Nullable<System.DateTime> CurDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ReschedAtty { get; set; }
        public Nullable<int> ReschedTsk { get; set; }
        public Nullable<int> ReschedApmtOffice { get; set; }
        public Nullable<int> ReschedBy { get; set; }
    }
}
