//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurisdiction
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string WebAddr { get; set; }
        public string Abbr { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ActiveCaseType { get; set; }
        public Nullable<bool> County { get; set; }
        public Nullable<int> CountyArea { get; set; }
        public Nullable<int> OfficeGrp { get; set; }
        public Nullable<bool> PrayerExempt { get; set; }
        public Nullable<long> LastPull { get; set; }
        public Nullable<int> intCurYr { get; set; }
        public Nullable<int> intRange { get; set; }
        public Nullable<int> intTmOut { get; set; }
    }
}
