//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurisdiction
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string WebAddr { get; set; }
        public string Abbr { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsCounty { get; set; }
        public Nullable<int> CountyID { get; set; }
        public Nullable<bool> PrayerExempt { get; set; }
        public Nullable<int> ChkRange { get; set; }
        public Nullable<long> LastRecNo { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public string LastRunStatus { get; set; }
    }
}
