//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurisdiction
    {
        public int ID { get; set; }
        public Nullable<int> OfficeGrp { get; set; }
        public string Jurisdiction1 { get; set; }
        public string URLString { get; set; }
        public string BtnLabel { get; set; }
        public Nullable<bool> Active { get; set; }
        public string txtMessage { get; set; }
        public Nullable<bool> County { get; set; }
        public Nullable<int> CountyArea { get; set; }
        public Nullable<long> Tag { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<bool> SiteType { get; set; }
        public Nullable<bool> MultiPage { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<bool> AutoIncr { get; set; }
        public Nullable<bool> PrayerExempt { get; set; }
        public Nullable<bool> ScrapeTxt { get; set; }
        public Nullable<long> LastPull { get; set; }
        public Nullable<int> intCurYr { get; set; }
        public Nullable<int> intRange { get; set; }
        public Nullable<int> intTmOut { get; set; }
    }
}
