//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseType> CaseTypes { get; set; }
        public virtual DbSet<chkCityName> chkCityNames { get; set; }
        public virtual DbSet<ChkNmSfx> ChkNmSfxes { get; set; }
        public virtual DbSet<ChkText> ChkTexts { get; set; }
        public virtual DbSet<CivilWkMnth> CivilWkMnths { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<IC_CN_Reason> IC_CN_Reason { get; set; }
        public virtual DbSet<ICCallLog> ICCallLogs { get; set; }
        public virtual DbSet<ICCallLog1> ICCallLog1 { get; set; }
        public virtual DbSet<ICCallLogCAN> ICCallLogCANs { get; set; }
        public virtual DbSet<ICCallLogCB> ICCallLogCBs { get; set; }
        public virtual DbSet<ICCallLogDelete> ICCallLogDeletes { get; set; }
        public virtual DbSet<ICCallLogFU> ICCallLogFUs { get; set; }
        public virtual DbSet<ICCallLogN> ICCallLogNS { get; set; }
        public virtual DbSet<ICCallLogRL> ICCallLogRLs { get; set; }
        public virtual DbSet<ICCallLogR> ICCallLogRS { get; set; }
        public virtual DbSet<ICSource> ICSources { get; set; }
        public virtual DbSet<ICStatu> ICStatus { get; set; }
        public virtual DbSet<Jurisdiction> Jurisdictions { get; set; }
        public virtual DbSet<Lawyer> Lawyers { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<OfficeArea> OfficeAreas { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Offices2> Offices2 { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<WBCT12> WBCT12 { get; set; }
        public virtual DbSet<spt_values> spt_values { get; set; }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    }
}
