//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ICLkUp
    {
        public string First_Name { get; set; }
        public string MInit { get; set; }
        public string Last_Name { get; set; }
        public string Case_No { get; set; }
        public string Case_Type { get; set; }
        public long ID { get; set; }
    }
}
