//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LetterInfo
    {
        public long DucumentID { get; set; }
        public string CaseNo { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public int DocketFrom { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMInit { get; set; }
        public string ContactLastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public Nullable<double> PrayerAmt { get; set; }
        public string Plaintiff { get; set; }
        public string PlaintAddr { get; set; }
        public string PlainAtt { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> LtrVer { get; set; }
    }
}
