//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBCT12
    {
        public long DucumentID { get; set; }
        public string DocTrackID { get; set; }
        public string CaseNo { get; set; }
        public string CaseType { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public int DocketFrom { get; set; }
        public string Judge { get; set; }
        public Nullable<System.DateTime> ServDate { get; set; }
        public Nullable<double> PrayerAmt { get; set; }
        public string CaseDesignation { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMInit { get; set; }
        public string ContactLastName { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Plaintiff { get; set; }
        public string PlaintAddr { get; set; }
        public string PlainAtt { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<System.DateTime> LtrSent { get; set; }
        public byte[] ServiceProof { get; set; }
        public Nullable<bool> ServiceYN { get; set; }
        public string DefaultTitle { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<bool> Merge { get; set; }
        public string BatchName { get; set; }
        public string EnvlName { get; set; }
        public Nullable<int> LtrVer { get; set; }
        public Nullable<System.DateTime> DatePrt { get; set; }
        public Nullable<bool> ReqMod { get; set; }
        public Nullable<bool> ModPrt { get; set; }
        public Nullable<System.DateTime> DateMod { get; set; }
        public string LblName { get; set; }
        public Nullable<bool> DNS { get; set; }
        public string BarCode { get; set; }
        public string HumanReadable { get; set; }
        public Nullable<bool> PrtDocket { get; set; }
        public Nullable<bool> Printed2 { get; set; }
        public Nullable<bool> Export { get; set; }
        public Nullable<bool> Export2 { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
